from resource import Resource
from resource_recipe import Recipe

resource_dict = {'apple': Resource(name = 'apple', consumption_utility = 1, decay = 0.8, health_points = 10,
                                   recipe = Recipe(time = 1, 
                                                   inputs = [], 
                                                   input_units = [], 
                                                   output = 'apple', 
                                                   output_units = 2,
                                                   requires_location = True)),
                'fish':   Resource(name = 'fish',  consumption_utility = 0.5, decay = 0.4, health_points = 5,
                                   recipe = Recipe(time = 1, 
                                                   inputs = [], 
                                                   input_units = [], 
                                                   output = 'fish', 
                                                   output_units = 1,
                                                   requires_location = True)),
                'wood':   Resource(name = 'fish',  consumption_utility = 0, decay = 0.95, health_points = -10,
                                   recipe = Recipe(time = 1, 
                                                   inputs = [], 
                                                   input_units = [], 
                                                   output = 'wood', 
                                                   output_units = 2,
                                                   requires_location = True)),
                'cooked fish':   Resource(name = 'cooked fish',  consumption_utility = 2.5, decay = 0.6, health_points = 20,
                                   recipe = Recipe(time = 1, 
                                                   inputs = ['wood','fish'], 
                                                   input_units = [1,2], 
                                                   output = 'cooked fish', 
                                                   output_units = 2,
                                                   requires_location = False)),}

